version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dnd_postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    container_name: dnd_fastapi
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

volumes:
  postgres_data:
