name: CI Pipeline

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build_image
        run: |
          docker buildx build \
            --file Dockerfile \
            --tag your-local-image:latest \
            --load .

      - name: Export Docker image to .tar file
        run: docker save your-local-image:latest -o your-local-image.tar

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-image
          path: your-local-image.tar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: built-image

      - name: Load Docker image
        run: docker load -i your-local-image.tar

      - name: Run tests in Docker container
        run: |
          docker run --rm your-local-image:latest python -m unittest discover -s __tests__ -p "*.py"
