name: CI Pipeline

on:
  push:
    branches:
      - main
      - test

jobs:
  build:

    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        id: build_image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/python-app:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository_owner }}/python-app:latest \
            --push .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: docker pull ghcr.io/${{ github.repository_owner }}/python-app:${{ github.sha }}

      - name: Run tests in Docker container
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/python-app:${{ github.sha }} python -m unittest discover -s __tests__ -p "*.py"
          
  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: docker pull ghcr.io/${{ github.repository_owner }}/python-app:${{ github.sha }}

      - name: Run lint in Docker container
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/python-app:${{ github.sha }} pylint src/
